// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var empty = /* Trie */{
  _0: undefined,
  _1: /* [] */0
};

var example = /* Trie */{
  _0: undefined,
  _1: {
    hd: [
      /* 'i' */105,
      /* Trie */{
        _0: 11,
        _1: {
          hd: [
            /* 'n' */110,
            /* Trie */{
              _0: 5,
              _1: {
                hd: [
                  /* 'n' */110,
                  /* Trie */{
                    _0: 9,
                    _1: /* [] */0
                  }
                ],
                tl: /* [] */0
              }
            }
          ],
          tl: /* [] */0
        }
      }
    ],
    tl: {
      hd: [
        /* 't' */116,
        /* Trie */{
          _0: undefined,
          _1: {
            hd: [
              /* 'e' */101,
              /* Trie */{
                _0: undefined,
                _1: {
                  hd: [
                    /* 'n' */110,
                    /* Trie */{
                      _0: 12,
                      _1: /* [] */0
                    }
                  ],
                  tl: {
                    hd: [
                      /* 'd' */100,
                      /* Trie */{
                        _0: 4,
                        _1: /* [] */0
                      }
                    ],
                    tl: {
                      hd: [
                        /* 'a' */97,
                        /* Trie */{
                          _0: 3,
                          _1: /* [] */0
                        }
                      ],
                      tl: /* [] */0
                    }
                  }
                }
              }
            ],
            tl: {
              hd: [
                /* 'o' */111,
                /* Trie */{
                  _0: 7,
                  _1: /* [] */0
                }
              ],
              tl: /* [] */0
            }
          }
        }
      ],
      tl: {
        hd: [
          /* 'A' */65,
          /* Trie */{
            _0: 15,
            _1: /* [] */0
          }
        ],
        tl: /* [] */0
      }
    }
  }
};

exports.empty = empty;
exports.example = example;
/* No side effect */
